#! /usr/bin/env bash

access_key_id=$(pass-field www/aws "Access Key ID")
secret_access_key=$(pass-field www/aws "Secret Access Key")

echo "{ \"Version\": 1, \"AccessKeyId\": \"$access_key_id\", \"SecretAccessKey\": \"$secret_access_key\" }"
