#! /usr/bin/env bash

set -e

PASS_RESOURCE=www/github
BASE_DIR=~/nfs-home/github-backup
USER=$(pass-username $PASS_RESOURCE)
PASS=$(pass-password $PASS_RESOURCE)
DEST_DIR=$BASE_DIR/$USER

mkdir -p $DEST_DIR
cd $DEST_DIR

github-backup $USER -u $USER -p $PASS --all -PFi --pull-details --gists
