#! /usr/bin/env sh

mail=$(for dir in ~/mail/*; do
    biff="$dir/biff.txt"
    if [ -r "$biff" -a -f "$biff" ]; then
        biffname=`cat $biff`
    else
        biffname=`basename $dir`
    fi
    printf " $biffname: "
    maildir-count "$dir"
done | grep -v ": 0" | paste -sd" ")
[ -z "$mail" ] || echo $mail
