#! /usr/bin/env sh

user_agent="Mozilla/5.0 AppleWebKit (KHTML, like Gecko) Chrome Safari"
export http_proxy=$PRIVOXY_URL; sudo -u $SANDBOX_USER -- bash -l -c "google-chrome-stable --user-agent==\"$user_agent\" \"$@\""
