#! /usr/bin/env bash

type=$1

cd
for i in dotfiles/dotfiles-$type/*; do
    dest=.`basename $i`
    if [[ -e $dest ]]; then
        echo ERROR: file already exists: $dest
    else
        echo ln -s $i $dest
    fi
done
