#! /usr/bin/env bash

cd
for i in dotfiles/dotfiles-common/*; do
    dest=.`basename $i`
    if [[ -e $dest ]]; then
        echo ERROR: file already exists: $dest
    else
        echo ln -s $i $dest
    fi
done
