#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

login=0
email=0
url=0
if [[ $1 == "--login" ]]; then
	login=1
	shift
elif [[ $1 == "--email" ]]; then
	email=1
	shift
elif [[ $1 == "--url" ]]; then
	url=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $login -eq 1 ]]; then
    passwordval=$(pass-login $password)
elif [[ $email -eq 1 ]]; then
    passwordval=$(pass-email $password)
elif [[ $url -eq 1 ]]; then
    passwordval=$(pass-url $password)
else
    passwordval=$(pass show $password | head -n 1)
fi

if [[ $typeit -eq 1 ]]; then
	xdotool - <<<"type --clearmodifiers -- $passwordval"
else
	echo do send passwordval to clipboard
fi
