#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

login=0
if [[ $1 == "--login" ]]; then
	login=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $login -eq 0 ]]; then
    passwordval=$(pass show $password | head -n 1)
else
    passwordval=$(pass-login $password)
fi

if [[ $typeit -eq 0 ]]; then
	echo do send passwordval to clipboard
else
	xdotool - <<<"type --clearmodifiers -- $passwordval"
fi
