#!/usr/bin/expect -f

set timeout 1
set exec [lindex $argv 0]
set name [lindex $argv 1]

set pass [exec pass $name 2>/dev/null | head -n1]

spawn $exec

expect {
    timeout { send_user "\nFailed to get password prompt\n"; exit 1 }
    eof { send_user "\nFailure for $exec\n"; exit 1 }
    "*assword"
}

send "$pass\r"
interact
