#! /usr/bin/env bash

prog=$(basename $0)
IFS=$'\n' read -d '' -r -a dirs < $1
IFS=$'\n' read -d '' -r -a cmds < ~/.config/$prog.d/"$2"

for r in "${dirs[@]}"; do
    expd=$(eval echo $r)
    for d in $expd; do
        if [[ -d $d ]]; then
            cd $d
            for c in "${cmds[@]}"; do
                ${prog%-batch} $c
            done
        fi
    done
done
