#! /usr/bin/env bash

SHA_0=$1
SHA_N=$2
BRANCH=${3-master}

git checkout $SHA_N
git reset --soft $SHA_0
git commit --amend
git tag SQUASH_TMP
git checkout $BRANCH
git rebase --onto SQUASH_TMP $SHA_N
git tag -d SQUASH_TMP
