#! /usr/bin/env bash

dir=$1

result="$(chk4mail -c -l -j -d $dir -e 'Trash' -e 'Junk Mail' -e 'Spam' -e 'Drafts' \
    | sed -e 's/^.* \([-0-9]\+\) \+new.*$/\1/g' \
    | sed -e 's/-/0/g' \
    | paste -sd+ \
    | bc)"
if [ -z "$result" ]; then
    result="0"
fi
echo $result
