#! /usr/bin/env sh

prg=`basename $0`
acc=$1
fld=$2

[[ -z $fld ]] && fld=${prg#pass-}

val=`pass $acc | egrep -i "^$fld:" | sed "s/^$fld:\(.*\)/\1/gI" | xargs`
echo -n $val
[[ -z "$val" ]] && exit 1 || exit 0
