#! /usr/bin/env expect

set t [lrange $argv 0 0]
set re [lrange $argv 1 1]
set pr [lrange $argv 2 2]
foreach a [lrange $argv 3 [llength $argv]] {
    lappend args [join $a]
}

set timeout $t
spawn -noecho [join $pr] $args
expect -re [join $re]

set stdin [gets stdin]
send -- "$stdin\r"
expect eof
